### ISSUE TITLE
DEADLINE_EXCEEDED in poller thread Activity Poller taskQueue="OrderLifecycleWorkflowTaskQueue", namespace="default": 5

### ISSUE THREAD

**Issue by satyasandipan** [datmt/temporal-microservices-demo#1]
Thanks for this sharing this repo. 
I just clone your repo and tried to run on my local setup.But I  am stuck at this line in OrderController.java

// Asynchronously start the workflow execution
        WorkflowClient.start(workflow::processOrder, request.customerId(), request.items(), amount);

Getting following error  - looks like WorkflowClient not able to start the workflow  

It would great if you can suggest me on following error 

[nio-7171-exec-2] i.t.s.WorkflowServiceStubsImpl           : Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=9, target=192.168.100.5:7233}}
2024-08-01T19:29:19.901+05:30  INFO 84589 --- [ce="default": 5] io.temporal.internal.worker.Poller       : DEADLINE_EXCEEDED in poller thread Activity Poller taskQueue="OrderLifecycleWorkflowTaskQueue", namespace="default": 5

io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 69.997818875s. [closed=[], open=[[remote_addr=/127.0.0.1:7233]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.pollActivityTaskQueue(WorkflowServiceGrpc.java:3801) ~[temporal-serviceclient-1.19.1.jar:na]
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:100) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:40) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:298) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.internal.worker.Poller$PollLoopTask.run(Poller.java:258) ~[temporal-sdk-1.19.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-08-01T19:30:04.633+05:30 ERROR 84589 --- [nio-7171-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: io.temporal.client.WorkflowServiceException: workflowId='bbf3130e-b375-4f46-9695-2db175612332', runId='', workflowType='OrderWorkflow'}] with root cause

io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.998139708s. [closed=[], open=[[buffered_nanos=10000515791, waiting_for_connection]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.53.0.jar:1.53.0]
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.getSystemInfo(WorkflowServiceGrpc.java:4141) ~[temporal-serviceclient-1.19.1.jar:na]
	at io.temporal.serviceclient.SystemInfoInterceptor.getServerCapabilitiesOrThrow(SystemInfoInterceptor.java:95) ~[temporal-serviceclient-1.19.1.jar:na]
	at io.temporal.serviceclient.ChannelManager.lambda$getServerCapabilities$3(ChannelManager.java:330) ~[temporal-serviceclient-1.19.1.jar:na]
	at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:60) ~[temporal-serviceclient-1.19.1.jar:na]
	at io.temporal.internal.client.external.GenericWorkflowClientImpl.start(GenericWorkflowClientImpl.java:69) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.internal.client.RootWorkflowClientInvoker.start(RootWorkflowClientInvoker.java:92) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:106) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowStubImpl.start(WorkflowStubImpl.java:131) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowInvocationHandler$StartWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:239) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:175) ~[temporal-sdk-1.19.1.jar:na]
	at jdk.proxy4/jdk.proxy4.$Proxy128.processOrder(Unknown Source) ~[na:na]
	at io.temporal.client.WorkflowClientInternalImpl.lambda$start$4875fa0c$1(WorkflowClientInternalImpl.java:337) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowClientInternalImpl.start(WorkflowClientInternalImpl.java:319) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowClientInternalImpl.start(WorkflowClientInternalImpl.java:337) ~[temporal-sdk-1.19.1.jar:na]
	at io.temporal.client.WorkflowClient.start(WorkflowClient.java:352) ~[temporal-sdk-1.19.1.jar:na]
	at com.datmt.temporal.orderservice.controllers.OrderController.createOrder(OrderController.java:34) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]

**Comment by datmt** [comment]
Hi @satyasandipan ,

I've updated the docker compose file in the readme. It seems there were some changes. Can you try running the temporal stack again?

**Comment by satyasandipan** [comment]
Hi @datmt 
Thanks for a quick turnaround. Earlier I had picked the docker compose file from this location 

https://github.com/temporalio/docker-compose/blob/main/docker-compose.yml

And as you suggested , I just picked only revision - rev: c66f523
  
Do you see any recent change , like temporal image version (you are pointing to) ?
